#!/bin/sh

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_tags.sh"

# github repo to get list of tags from
BASEREPO=s3fs-fuse/s3fs-fuse
MINVER=${MINVER:-1.78}
VERSIONS=${VERSIONS:-} # When empty, will be all version starting from $MINVER

if [ -z "$VERSIONS" ]; then
    VERSIONS=$( curl -qsL https://api.github.com/repos/${BASEREPO}/tags |
                grep "\"name\":" |
                sed "s/,$//g" |
                sed "s/^\s*\"name\":\s*//g" |
                sed "s/\"//g")
fi

for version in $VERSIONS; do
    official=$(echo "$version" | grep -E "^v[0-9]+(.[0-9]+)*")
    if [ -n "$official" ]; then
        tag=$(echo "$official" | sed "s/^v//g")
        if [ "$tag" = "1.87" ] || [ "$(img_version "$tag")" -lt "$(img_version "$MINVER")" ]; then
            echo "======================= Skipping ${DOCKER_REPO}:$tag, known to fail/too old"
        else
            echo "======================= Pushing ${DOCKER_REPO}:$tag"
            docker buildx build --push -t "${DOCKER_REPO}:$tag"
        fi
    fi
done
